config/routes.rb
Rails.application.routes.draw do

  resources :products do
    member do
      post "order" => 'products#order', :as => :order
      get "new"    => 'products#new',   :as => :new_child
    end
    collection do
      get 'report'
      post 'subscribe'
    end
  end

  resources :orders do
    member do
      get "status"
      get "download"
    end
  end

  root 'products#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :product
  belongs_to :shipping

  validates_presence_of :product_id, :bts_amount, :bts_asset_id
  validates_presence_of :shipping_id, :address, :unless => :is_dd?

  before_validation :add_total, :set_pub_id, :check_stock
  before_create :set_due_at

  def to_param
    pub_id
  end

  def self.from_param pub_id
    where(:pub_id => pub_id).order('id DESC').first or raise ActiveRecord::RecordNotFound.new("Couldn't find order #{pub_id}")
  end



  def is_dd?
    product.dl.exists?
  end

  def expired?
    !paid? && (due_at < DateTime.now)
  end

  def stale?
    paid? ? paid_at < 1.day.ago : expired?
  end

  def paid?
    !paid_at.nil?
  end

  def bts_url
     "bts:#{Wallet::ACCT}/transfer/amount/#{amount.amount}/memo/#{pub_id}/asset/#{amount.symbol}"
  end

  def amount
    Amount.from_bts({'amount' => bts_amount, 'asset_id' => bts_asset_id})
  end
  def amount=(amt)
    self.bts_amount   = amt.bts_amount
    self.bts_asset_id = amt.bts_asset_id
  end

 
 
  def set_due_at #before_create
    self.due_at = 15.minutes.from_now
  end

  def check_stock #before_validation
    errors.add(:product_id, "out of stock!") if product.sold_out?
  end

  def add_total #before_validation
    raise "No product selected" unless product
    raise "No asset selected" unless bts_asset_id
    amt = product.amount.convert(bts_asset_id)
    amt = amt.add(shipping.amount.convert(bts_asset_id)) if shipping
    self.amount = amt
  end

  def set_pub_id #before_validation
    return if pub_id 
    opts = %w{a x z t r k b e d q w e y u s p t 3 2 6 8}
    self.pub_id = (1..4).map{|i| opts.sample}.join.upcase
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_filter :load_order

  def show
    render 'stale' if @order.stale?
  end

  def status
    Wallet.scan

    render :js => case
      when @order.paid? && @order.is_dd?
        "notify_dl('#{download_order_url(@order)}');"
      when @order.paid?
        "notify_ship();"
      else
        ""
    end
  end

  def download
    raise "Order is stale"    if @order.stale?
    raise "Order is not paid" unless @order.paid?
    raise "Not downloadable"  unless @order.is_dd?

    p = @order.product
    send_file p.dl.path,
      :filename    => p.dl_file_name,
      :type        => p.dl_content_type,
      :disposition => 'attachment'
  end

private
  def load_order
    @order = Order.from_param(params[:id])
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/show.html.erb
<div class="row">

  <div class="col-sm-3">
    <div style="text-align: center;">
      <%= image_tag @order.product.root.image(:medium), :class => 'img-thumbnail-old', :style => "max-height: 240px; max-width: 190px;" %>
    </div>
  </div>

  <div class="col-sm-8" style="margin-bottom: 1em;">
    <h2><%= @order.product.root.name %> <small><%= @order.product.name %></small></h2>
  </div>

  <div class="col-sm-6">
    <div class="alert bg-info">
      <p class="lead" style="min-height: 80px;">
        <%= image_tag '/cashier.jpg', :class => 'pull-left img-thumbnail', :style => "max-height: 120px; margin-right: 16px;" %>
          To complete your order,
          send <code><%= @order.amount.short.gsub(' ', '&nbsp;').html_safe %></code> 
          to <code><%= Wallet::ACCT %></code> with 
          memo&nbsp;<code><%= @order.pub_id %></code>.
      </p>
      <p class="clearfix" style="padding-topx: 22px;">
        <%= link_to 'Pay with BitShares client', @order.bts_url, :class => 'btn btn-primary pull-right', :id => 'pay_button' %>
        <span id="timeleft" class="btn disabled pull-right"></span>
      </p>
    </div>

    <div class="alert well">
      <p id="status_alert" class="text-muted">
        <% if @order.shipping %>
          Item will be shipped to: <br />
          <%= @order.address.gsub(/[\r\n]+/, ", ") %>, 
          <%= @order.shipping.name %> 
          <%# local_price(@order.shipping) %>
        <% else %>
          Your download will begin within 10 seconds of payment.
        <% end %>
      </p>
    </div>


  </div>
</div>


<script>
  var isdone = false;
  var expires = new Date();
  <% seconds = (@order.due_at - DateTime.now).seconds %>
  expires.setSeconds(expires.getSeconds() + <%= seconds %>);

  function notify_dl(url) {
    _done('Thank you! If your download did not start automatically, <a href="'+url+'">try again</a>');
    <%= "if(url != '') window.location = url;".html_safe unless @order.paid_at %>
  }

  function notify_ship() {
    _done("Thank you for your order! It will be shipping soon!");
  }

  function notify_expired() {
    _done('Expired!');
  }

  // Received a message; stop polling.
  function _done(status_html) {
    if(isdone) return;
    isdone = true;
    $('#pay_button').hide();
    $('#timeleft').html("This order will now self-destruct."); 
    $('#status_alert').html(status_html);
  }

  $(document).ready(function() {

    <%# Update the countdown once a second %>
    <% if seconds > 0 %>
    var countdown = setInterval(function(){ 
      if(isdone) {
        clearInterval(countdown); 
        return;
      }

      var seconds = (expires - (new Date()).getTime()) / 1000;
      if(seconds <= 0) {
        notify_expired();
        return;
      }

      var m = Math.floor(seconds / 60),
          s = Math.floor(seconds % 60);
      $('#timeleft').html( (m > 0 ? m + "m " : "") + s + "s remaining" ); 
    }, 1000);
    <% end %>

    <%# Poll the server every 5 seconds %> 
    function poll() {
      if(isdone) return;
      setTimeout(function(){
        $.getScript("<%= status_order_url(@order.pub_id) %>")
         .done(function( script, textStatus ) {poll();})
         .fail(function( jqxhr, settings, exception ) {
           alert("Could not contact server. Please refresh the page.");});
      }, 5000);
    }
    poll();

  });
</script>

app/views/orders/stale.html.erb
This order has expired, is stale (completed more than 24h ago), or does not exist.