config/routes.rb
Rails.application.routes.draw do

  resources :products do
    member do
      post "order" => 'products#order', :as => :order
      get "new"    => 'products#new',   :as => :new_child
    end
    collection do
      get 'report'
      post 'subscribe'
    end
  end

  resources :orders do
    member do
      get "status"
      get "download"
    end
  end

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base

  has_attached_file :dl, 
    :styles      => {},
    :url         => "/system/:class/:attachment/:id_partition/:style_:hash.:extension",
    :hash_data   => ":class/:attachment/:id/:style",
    :hash_secret => STORE['secret_phrase']
  
  # .mobi = application/octet-stream
  validates_attachment :dl, content_type: { content_type: ["application/pdf", "image/jpeg", "application/octet-stream", "application/epub+zip"] }

  has_attached_file :image, 
    :styles      => { :medium => "300x300>", :thumb => "100x100>" }, 
    :url         => "/system/:class/:attachment/:id_partition/:style_:hash.:extension",
    :hash_data   => ":class/:attachment/:id/:style",
    :hash_secret => STORE['secret_phrase']
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_many :orders
  has_many :photos

  accepts_nested_attributes_for :photos, :reject_if => lambda { |t| t['image'].blank? }, :allow_destroy => true

  #self.inheritance_column = :node_type

  def num_sold
    orders.select{|o| o.paid?}.size
  end

  def num_locked
    orders.select{|o| !o.paid? && !o.expired?}.size
  end

  def num_left
    return 9999 unless num_stock
    (num_stock - num_sold)
  end

  def sold_out?
    return false unless num_stock
    num_left <= 0
  end

  def all_images
    #self_and_descendants.select{|p| p.image.exists?}.map{|p| p.image}
    out = []
    out << image if image.exists?
    out += photos.map(&:image)
    out
    photos.any? ? photos.map(&:image) : (image.exists? ? [image] : [])
  end

  def priced?
    !cents.nil?
  end

  def amount
    Amount.cent(cents) if cents
  end

  def new_order
    Order.new(:product_id => id)
  end

  def self.categories
    Product.where(:parent_id => nil).order(:position)
  end

  def root?
    parent_id.nil?
  end
  
  def root
    parent_id ? Product.find(parent_id) : self
  end

  def depth
    return 0 unless parent_id
    1 + Product.find(parent_id).depth
  end

  def children
    Product.where(:parent_id => id)
  end

  def self_and_descendants
    [self] + children.map{|c| c.self_and_descendants}.flatten
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  http_basic_authenticate_with name: STORE['admin_user'], password: STORE['admin_pass'], except: [:subscribe, :index, :show, :order]

  def subscribe
    sub = Subscription.new(subscription_params)
    redirect_to root_url, notice: (sub.save ? "Subscribed!" : "Invalid entry.")
  end

  def index
    @products = Product.categories
  end

  def show
    @product = Product.find(params['id'])
    if @product.children.size == 1
      redirect_to @product.children.first
    else
      @order = @product.new_order
    end
  end

  def order
    @order = Order.new(order_params.merge(
      :ip            => request.remote_ip, 
      :referrer_acct => cookies[:referer], 
      :bts_asset_id  => session[:asset]))

    if @order.save
      redirect_to @order
    else
      @product = @order.product
      render 'show'
    end
  end


  def report
  end

  def new
    @product = Product.new(:parent_id => params[:id])
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product, notice: "All good!"
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params['id'])
  end

  def update
    @product = Product.find(params['id'])
    if @product.update_attributes(product_params)
      redirect_to edit_product_url, notice: "All good!"
    else
      render 'edit'
    end
  end

private

  def subscription_params
    params.require(:subscription).permit(:email)
  end

  def order_params
    params.require('order').permit(:product_id, :shipping_id, :address, :email)
  end

  def product_params
    params.require('product').permit(:name, :desc, :parent_id,
       :cents, :position, :default_id, :dl, :image, :is_category, :code, :short_desc,
       :button_label, :num_stock, :num_sold, :node_type, :royalty_acct, :royalty_cents, :refer_cents, 
       :photos_attributes => [:image, :_destroy, :id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product, :html => {:role => 'form', :style => "width: 800px;", :multipart => true} do |f| %>

    <% if @product.errors.any? %>
      <strong style="color: #C00;">Oops!</strong>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>

<!--
  <%# TODO: Implement this! %>
  <div class="form-group">
    <%= f.label :node_type %><br />
    <%= f.select :node_type, {"Category (Container for products)" => "Category", "Product" => "Product", "Product Variant" => "Variant"}, :include_blank => true %>
  </div>
-->

  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, :size => 40, :class => 'xform-control' %>
  </div>

  <div class="form-group">
    <%= f.label :parent_id, "Parent/Category" %><br />
    <%= f.select :parent_id, Product.all.reject{|p| p.depth > 0}.map{|p| [p.name, p.id]}, :include_blank => "(top-level)" %>
  </div>

  <div class="form-group">
    <%= f.label :position, "Sort order (1..n)" %><br />
    <%= f.text_field :position %>
  </div>






  <% if @product.root? %>






    <div class="form-group">
      <%= f.label :button_label %><br />
      <%= f.text_field :button_label %>
    </div>
    <div class="form-group">
      <%= f.label :short_desc, "Short Description (HTML)" %><br />
      <%= f.text_area :short_desc, :class => 'xform-control', :rows => 3, :cols => 100 %>
    </div>
    <div class="form-group">
      <%= f.label :desc, "Description (HTML)" %><br />
      <%= f.text_area :desc, :class => 'xform-control', :rows => 6, :cols => 100 %>
    </div>

    <div class="well"> 
      <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image, :class => 'form-control' %>
      </div>
      <% if @product.image.exists? %>
        <%= image_tag @product.image(:thumb), :class => 'img-thumbnail' %> this is the front page/feature image. if you upload another it gets replaced.
      <% end %>
    </div>

    <% [1, 5-@product.photos.size].max.times{@product.photos.build} %>

    <div class="well" style="height: 100%; overflow: hidden;"> 
      <%= f.label :photos %><br />
      <%= f.fields_for :photos do |f2| %>
        <div style="float: left; width: 140px; height: 130px; text-align: center; margin: 2px;" class="img-thumbnail">
          <% if f2.object.image.exists? %>
            <div style="width: 100px; height: 100px; background: #EEE; display: inline-block;">
              <%= image_tag f2.object.image(:thumb), :class => 'img-thumbnails' %>
            </div><br />
            <%= f2.check_box :_destroy %> Destroy?
          <% else %>
            <div style="width: 100px; height: 75px; background: #EEE; display: inline-block;"></div>
            <%= f2.file_field :image, :class => 'form-control' %>
          <% end %>
          <%= f2.hidden_field :id %>
        </div>
      <% end %>
    </div>




  <% else %>




    <% unless @product.dl.exists? %>
      <div class="form-group">
        <%= f.label :num_stock, "Stock count" %><br />
        <%= f.text_field :num_stock %>
        Sold: <%= @product.num_sold %>  Locked: <%= @product.num_locked %>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :cents %><br />
      <%= f.number_field :cents, :class => 'xform-control' %> 
    </div>

    <div class="well"> 
      <div class="form-group">
        <%= f.label :dl, "Digital Download (PDF only)" %>
        <%= f.file_field :dl, :class => 'form-control' %>
      </div>
      <% if @product.dl.exists? %>
        <p class="text-primary">ACHTUNG! There is an existing digital download: <%= @product.dl_file_name %>. Uploading will replace this file.</p>
      <% end %>
    </div>




  <% end %>





  <%= f.submit 'Save Changes', :class => 'btn btn-success' %>

<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<hr />

<%
  def list(parent_id = nil)
    out = []
    Product.where(:parent_id => parent_id).order('position').each do |h|
      link = link_to_unless(@product == h, h.name, edit_product_url(h))
      sold = case
        when h.num_stock    then "#{h.num_sold} of #{h.num_stock}"
        when h.num_sold > 0 then "#{h.num_sold}"
        else ""
      end
      out << "<li><div class=\"pull-right\">#{sold}</div> #{link} #{list h.id}</li>"
    end
    "<ul>#{out.join}</ul>" unless out.size == 0
  end
%>

<div class="pull-right">
  <div class="pull-right">Sold</div>
  <div style="clear: both;"></div>
  <%= list.html_safe %>
</div>

<%= render :partial => 'form' %>

app/views/products/index.html.erb
<style>
#product_list .jumbotron {padding: 24px 30px;}
#product_list h2 a {color: inherit;}
#product_list h2 {margin-top: 0;}
#product_list h3 {margin-top: 0;}
#product_list p {font-size: 1.2em;}
#product_list div.text {min-height: 90px;}
#product_list .image {width: 200px; height: 200px; border: 1px solid #fff; position: relative; background: white;}
#product_list .image img {max-height: 100%; max-width: 100%; margin: 0 auto; display: block;}
#product_list .image .bg {position: absolute; top: 0; right: 0; width: 100%; height: 100%; z-index: 10; box-shadow: -3px -6px 40px -10px #ddd inset;}
</style>


<div id="product_list">

  <% @products.each do |p| %>
    <div class="jumbotron">
      <div class="row">
        <div class="col-sm-4 col-md-3">
          <div class="image">
            <%= link_to image_tag(p.image.url(:medium)), p %>
            <%= link_to "", p, :class => 'bg' %>
          </div>
        </div>

        <div class="col-sm-8 col-md-9">
          <h2><%= link_to p.name, p %></h2>
          <div class="text">
            <%= p.short_desc.html_safe %>
          </div>
          <span class="pull-right <%= "bts-text-#{session[:asset].downcase}" %>">
            <% cheapest = p.children.sort_by{|c| c.cents}.first %>
            <big><%= p.children.size > 1 ? 'Starting at' : '' %> <%= local_price(cheapest, true) %></big>
          </span>
          <p><%= link_to (!p.button_label.blank? ? p.button_label : 'Check it out &rarr;'.html_safe), p, :class => 'btn btn-primary xbtn-lg' %></p>
        </div>
      </div>
    </div>
  <% end %>

  <div class="jumbotron">
    <div class="row">
      <div class="col-sm-4 col-md-3">
        <div class="image">
          <%= image_tag "/mystery.jpg" %>
          <div class="bg"></div>
        </div>
      </div>

      <div class="col-sm-8 col-md-9">
        <h3>More coming soon</h3>
        <br />
        <p>More BitShares swag will be here soon!</p>
        <br />
        For updates check <a href="https://bitsharestalk.org/">BitSharesTalk</a>, or sign up below:<br />
        <%= form_for :subscription, :url => subscribe_products_url, :html => {:class => 'form-inline', :role => 'form'} do |f| %>
          <%= f.text_field :email, :size => 32, :placeholder => "satoshi@gmail.com", :class => 'form-control' %> 
          <%= f.submit "Get updates", :class => 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render :partial => 'form' %>

app/views/products/report.html.erb
<style>
.fee {float: right; color: #CCC; font-size: 0.9em; padding-left: 3px;}
</style>

<h3>Transactions</h3>
<table class="table table-bordered" style="font-size: 9pt; width: auto;">
  <tr>
    <td>trx</td>
    <td>block</td>
    <td>date</td>
    <td>amount <span class="fee">fee</span></td>
    <td align="center">from &rarr; to</td>
    <td>status</td>
    <td>memo</td>
  </tr>

<% 

ids = Hash[Order.all.map{|o| [o.pub_id, o]}]
Tx.all.sort_by{|tx| tx.block_num}.reverse.each do |tx| 
  tx = tx.ledger_entry
  id = ids.keys.find{|i| tx['memo'].include?(i)}
  o  = id ? ids[id] : nil
  status = case
    when !o then ""
    when (Amount.from_bts(tx['amount']).includes?(o.amount) rescue false)  then "PAID"
    else "INVALID"
  end
  paid = status == "PAID"
%>
  <tr>
    <td><%= tx['trx_id'][0..8] %></td>
    <td><%= tx['block_num'] %></td>
    <td><%= tx['date'] %></td>
    <td>
      <span class="fee">
        <%= Amount.from_bts(tx['fee']).short %>
      </span>
      <%= Amount.from_bts(tx['amount']).short %>
    </td>
    <td align="right"><%= "#{tx['from'].gsub('cashier as cashier', 'cashier')} &rarr; #{tx['to']}".gsub(Wallet::ACCT, "<strong>\\0</strong>").html_safe %></td>
    <% memo = tx['memo'] %>
    <% memo = o ? memo.gsub(o.pub_id, "<strong style=\"color: #080; font-weight: normal;\">\\0</strong>") : "#{memo} <strong style=\"color: #C00;\"></strong>" %>
    <td align="center"><%= (paid ? "<strong style=\"color: #080;\">PAID</strong>" : "<strong style=\"color: #C00; font-weight: normal;\">invalid</strong>").html_safe %>
    <td><%= memo.html_safe %></td>
  </tr>

<% end %>
</table>

<br />
<hr />

<h3>Orders</h3>

<%= DateTime.now %>
<table class="table table-bordered" style="font-size: 9pt;">
  <thead>
    <tr>
      <td>id</td>
      <td>ID</td>
      <td>product</td>
      <td>price</td>
      <td>paid?</td>
      <td>paid by</td>
      <td>created</td>
      <td>shipping</td>
      <td>ip, referer</td>
    </tr>
  </thead>
<% Order.all.order('created_at DESC').reject{|o| o.due_at < 24.hours.ago && !o.paid?}.each do |o| %>
  <%
    status = case
      when o.paid?    then ''
      when o.expired? then 'Expired'
      else "DUE in #{((o.due_at - DateTime.now)/60).round(1)}m"
    end
  %>
  <tr>
    <td><%= o.id %></td>
    <td><%= o.pub_id %></td>
    <td><%= "<small><strong>#{o.product.root.name}</strong></small><br/>#{o.product.name}</small>".html_safe rescue 'Unknown' %></td>
    <td><%= o.amount.short rescue '??' %></td>
    <td>
      <%= o.paid_at.strftime("%Y-%m-%d %H:%M") rescue '' %>
      <%= status %>
    </td>
    <% tx = Tx.where(:trx_id => o.trx_id).first %>
    <td><%= (tx ? tx.ledger_entry['from'] : '') %></td>
    <td><%= o.created_at.strftime("%Y-%m-%d %H:%M") %></td>
    <td><%= h(o.address).gsub("\n","<br />").html_safe %></td>
    <td><small><%= o.ip %></small><br /><%= o.referrer_acct %></td>
  </tr>
<% end %>

</table>

app/views/products/show.html.erb
<style>
.product-name      {margin: 0 0 22px;}
form .form-control {margin-bottom: 1em;}
.field_with_errors {background: #FDD;}
.image             {width: 100%; border: 1px solid #fff; box-shadow: -3px -6px 80px -10px rgba(0,0,0,0.2) inset; float: left; max-height: 302px;}
.image img         {max-height: 300px; margin: 0 auto; display: block; z-index: -5; position: relative; max-width: 100%;}
.variant           {border: 1px solid #AAA; display: inline-block; padding: 0.2em 0.6em; margin: 0.2em 0.1em;}
span.variant       {font-weight: bold;}
.img-thumbnail     {max-height: 50px; margin: 2px 1px;}
</style>

<% @root = @product.root %>

<%= form_for @order, :url => order_product_url(@product), :html => {:role => :form} do |f| %>
  <div class="row">
    <div class="col-md-5" id="images">
      <% imgs = @root.all_images %>
      <div class="image">
        <%= image_tag imgs[0].url(:medium), :id => 'main_image' %>
      </div>
      <% imgs.each do |img| %>
        <%= link_to image_tag(img.url(:thumb), :class => 'img-thumbnail'), img.url(:medium) %>
      <% end %>
    </div>
    <script>
      var pimg, mel = $('#main_image');
      function setimg(url) {pimg = mel.attr('src'); mel.attr('src', url);}
      function resimg() {if(pimg) mel.attr('src', pimg);}
      $('#images a').on('click', function() {pimg = null; return false;});
      $('#images a').on('mouseover', function() {
        setimg($(this).attr('href')); 
        //$(this).one('mouseout', resimg);
        return false;
      });
    </script>

    <div class="col-md-6" style="margin-bottom: 1em;">
      <h2 class="product-name"><%= @root.name %></h2>
      <%= (@root.desc.blank? ? @root.short_desc : @root.desc).html_safe rescue '' %> 
      <% if @order.errors.any? %>
         <strong style="color: #C00;"><%= @order.errors.full_messages.join(' ') %></strong>
      <% end %>

      <%= f.hidden_field :product_id %>
      <% 
        rc   = @root.children 
        type = (@order.is_dd? ? "digital download" : "style")
        type = "select a #{type}:" if @product.root?
      %>
      <%= f.label :product_id, type, :class => (@product.root? ? "text-danger" : nil) %><br />
      <% unless @product.root? %>
        <span class="variant bg-info"><%= "#{@product.name} (#{local_price(@product)})" %></span>
        <%= link_to 'change', @root unless rc.size == 1 %>
      <% else %>
        <% rc.each do |p| %>
          <span style="display: inline-block; min-width: 9em;"><%= link_to p.name, p, :class => "xvariant" %></span>
          <% if p.num_left < 1 %>
            <span style="color: #C00;">Sold out!</span>
          <% else %>
            <span class="text-muted" style="color: #CCC;"><%= local_price(p) %></span>
          <% end %>
          <br />
        <% end %>
      <% end %>
      <br /><br />

    <% if @order.product.priced? %>
      <div class="row">
      <div class="col-md-6">
        <% unless @order.is_dd? %>
          <%= f.label     :address,      "ship to" %>
          <%= f.text_area :address, :rows => 3, :cols => 22, :placeholder => "Satoshi Nakamoto\n1101 Cipher St\nBlacksburg, VA", :class => 'form-control' %>
          <%= f.label     :shipping_id,  "shipping" %>
          <%= f.select    :shipping_id,  Hash[Shipping.all.map{|s| ["#{s.name.downcase} (#{local_price(s)})", s.id]}], {:include_blank => false}, {:class => 'form-control'} %>
          <%= f.submit   "Pay with Bit#{session[:asset]} &rarr;".html_safe, :class => 'btn btn-primary btn-lg' %>
        <% else %>
          <%= f.button "#{local_price(@product, true)} &rarr;".html_safe, :type => 'submit', :class => 'btn btn-primary btn-lg' %>
        <% end %>
        <% if session[:asset] == 'USD' %>
          <br />
          <br />
          <%= link_to "What is BitUSD?", "http://whatisbitusd.com/", :class => 'small', :rel => 'nofollow' %>
        <% end %>
      </div>
      </div>
    <% end %>

    </div>

    <%# link_to "Edit", edit_product_url(@product) %>
  </div>
<% end %>